// rberenguel/eixut/eixut-4ac6548c249ebe36481b419891e1f9d663f25fb5/js/modules/state.js
import { PLAYER_HEALTH, PLAYER_DAMAGE } from "./constants.js";

export const state = {
  scene: null,
  camera: null,
  renderer: null,
  player: null,
  shield: null,
  arenaBounds: null,
  clock: new THREE.Clock(),
  enemies: [],
  bullets: [],
  sword: null,
  swordPivot: null,
  swordTip: null,
  attackRangeIndicator: null,
  swordTrailParticles: [],
  swordTrailContainer: null,
  explosionParticles: [],
  explosionContainer: null,
  splatters: [],
  splatterContainer: null,
  playerHealth: PLAYER_HEALTH,
  enemiesKilled: 0,
  sphereEnemyCount: 0,
  playerInvincibilityTimer: 0,
  attackCooldownTimer: 0,
  shieldTimer: 0,
  screenShakeTimer: 0,
  arenaBorderFlashTimer: 0,
  cameraOffset: new THREE.Vector3(0, 15, 15),
  isHolding: false,
  isHardCharging: false,
  isDashing: false,
  isAttacking: false,
  isFirstSwordFrame: true,
  currentAttackDamage: PLAYER_DAMAGE,
  gameState: "paused", // 'paused', 'playing', 'playerDying', 'gameOver'
  gameOverTimer: 0,
  dashStartPosition: new THREE.Vector3(),
  dashDirection: new THREE.Vector3(),
  targetQuaternion: new THREE.Quaternion(),
  attackStartPosition: new THREE.Vector3(),
  attackDirection: new THREE.Vector3(),
  swipeStartTime: 0,
  holdStartTime: 0,
  swordRotationTimer: 0,
  nextTrailParticleIndex: 0,
  nextExplosionParticleIndex: 0,
  nextSplatIndex: 0,
  hitEnemiesInAttack: [],
  startCoords: null,
  lastSwordTipPosition: new THREE.Vector3(),
  reusableVector1: new THREE.Vector3(),
  reusableVector2: new THREE.Vector3(),
  reusableVector3: new THREE.Vector3(),
  map: null,
  currentRoom: { x: 0, y: 0 },
  obstacles: [],
  doors: {},
  isTransitioning: false,
  transitionTimer: 0,
  nextRoomData: null,
};
